### ISSUE TITLE
Bug in bitplane buffer size

### ISSUE THREAD

**Issue by paulreimer** [pixelmatix/esp32_I2sParallelDmaLedMatrix#1]
https://github.com/pixelmatix/esp32_I2sParallelDmaLedMatrix/blob/3ed8343244cbba76841d2d99c310f04571735cc3/main/app_main.c#L162

s/matrixHeight/matrixWidth/

**Comment by paulreimer** [comment]
Actually it wasn't clear what values should be swapped, but the current `master` HEAD crashes with out-of-bounds accesses, when matrixWidth != 32 e.g. `#define matrixWidth 64`.

**Comment by themindfactory** [comment]
I have set width to 32 and height to 16 and I get this output on serial before crash...

buffer 4: repeat 4 times, size: 3, from 4 - 6

i 4, j 8, k 0

i 4, j 8, k 1

i 4, j 8, k 2

i 4, j 8, k 3

buffer 8: repeat 8 times, size: 2, from 5 - 6

i 5, j 8, k 0

i 5, j 8, k 1

i 5, j 8, k 2

i 5, j 8, k 3

i 5, j 8, k 4

i 5, j 8, k 5

i 5, j 8, k 6

i 5, j 8, k 7

buffer 16: repeat 16 times, size: 1, from 6 - 6

i 6, j 8, k 0

i 6, j 8, k 1

i 6, j 8, k 2

i 6, j 8, k 3

i 6, j 8, k 4

i 6, j 8, k 5

i 6, j 8, k 6

i 6, j 8, k 7

i 6, j 8, k 8

i 6, j 8, k 9

i 6, j 8, k 10

i 6, j 8, k 11

i 6, j 8, k 12

i 6, j 8, k 13

i 6, j 8, k 14

i 6, j 8, k 15

row 9: 

buffer 1: repeat 1 times, size: 5, from 2 - 6

i 2, j 9, k 0

buffer 2: repeat 2 times, size: 4, from 3 - 6

i 3, j 9, k 0

i 3, j 9, k 1

buffer 4: repeat 4 times, size: 3, from 4 - 6

i 4, j 9, k 0

i 4, j 9, k 1

i 4, j 9, k 2

i 4, j 9, k 3

buffer 8: repeat 8 times, size: 2, from 5 - 6

i 5, j 9, k 0

i 5, j 9, k 1

i 5, j 9, k 2

i 5, j 9, k 3

i 5, j 9, k 4

i 5, j 9, k 5

i 5, j 9, k 6

i 5, j 9, k 7

buffer 16: repeat 16 times, size: 1, from 6 - 6

i 6, j 9, k 0

i 6, j 9, k 1

i 6, j 9, k 2

i 6, j 9, k 3

i 6, j 9, k 4

i 6, j 9, k 5

Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited)
. Exception was unhandled.
Register dump:
PC      : 0x00000040  PS      : 0x00060930  A0      : 0x8000bd86  A1      : 0x3ffcbce0  
A2      : 0x3ffcff40  A3      : 0x00000040  A4      : 0x3ffc72d8  A5      : 0x0000000f  
A6      : 0x3ffc482c  A7      : 0x00000040  A8      : 0x800d50b0  A9      : 0x3ffcbcc0  
A10     : 0x00000000  A11     : 0x3ffc72d8  A12     : 0x0000000f  A13     : 0x3f414948  
A14     : 0x3ffcbdf0  A15     : 0x00000003  SAR     : 0x00000004  EXCCAUSE: 0x00000014  
EXCVADDR: 0x00000040  LBEG    : 0x400014fd  LEND    : 0x40001

**Comment by themindfactory** [comment]
So if I get height and width to 32 and 32 its all OK, its only when height is 16 :-)

**Comment by themindfactory** [comment]
found the error:

in setup() there was for (int j = 0; j < matrixWidth / matrixRowsInParallel; j++)

should have been for (int j = 0; j < matrixHeight / matrixRowsInParallel; j++)

:-)

**Comment by embedded-creations** [comment]
Thanks for pointing out the issue and finding the bug.  I should have tested on multiple panel sizes but my current ESP32 setup is difficult to unplug from the 32x32 panel it's attached to.  I'll get this fixed and committed.

**Comment by themindfactory** [comment]
Yeah good work on the code, runs nicer than original in terms of ghosting.... still some funny green streaks when you move a single white dot around all by itself.... but once you get some other pixels lite it makes it less noticeable....

I also tweaked the code some more to get the building of the DMA buffer to execute faster, as my plans are to do some large panels and I need it as fast as possible.... it was building a 32x16 frame in 1100uS now its 700uS

Pretty amazing it runs at 500fps with a 8Mhz clock to the panel :-)

**Comment by embedded-creations** [comment]
@themindfactory I'm porting the SmartMatrix Library, and it has support for stacking panels to make a larger display, which may help for your project.  It's coming along and I should have a preliminary version to share shortly.  I'll post to the ESP32 thread.
